version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql
    networks:
      - mynetwork

  spring_app:
    image: imageproject
    container_name: containerDevops
    restart: on-failure
    ports:
      - 9092:8089
    depends_on:
      - mysqldb
    networks:
      - mynetwork

networks:
  mynetwork:
    external:
      name: mynetwork
